# Generated by Django 3.0.2 on 2020-02-04 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20200204_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='激活状态'),
        ),
        migrations.AlterField(
            model_name='member',
            name='exp_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 5, 9, 32, 16, 494391), verbose_name='Token过期时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_login_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 4, 9, 32, 16, 494391), verbose_name='上次登录时间'),
        ),
    ]
